# Generated by Django 5.2 on 2025-04-18 00:18

import utilisateurs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_profile',
            field=models.ImageField(blank=True, upload_to=utilisateurs.models.renommer_image),
        ),
    ]
